# Análisis Exploratorio de Datos (EDA)
## Calidad de Datos Abiertos en Colombia

Estudiante: Juan David Arboleda Molina  
Curso: Analítica de Datos  

Este proyecto realiza un análisis exploratorio del dataset
"Reporte de Calidad de Datos Abiertos 2025" con el objetivo
de identificar patrones, calidad de los datos y distribución
de los datasets publicados en el portal de datos abiertos de Colombia.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

Se importan las librerías necesarias para el análisis:

- pandas: manipulación de datos
- numpy: operaciones numéricas
- matplotlib: visualización
- seaborn: gráficos estadísticos

In [3]:
df = pd.read_csv("Vista_Reporte_de_Calidad_de_Datos_Abiertos_2025_20260315.csv")
df.head()

,Título,Tipo de activo,Suministró los datos,Categoría,Descripción,Etapa de publicación,Municipio,Nombre entidad,Orden,Departamento,Frequencia actualización,Fecha de creación,Fecha de publicación,Fecha última actualización,CALIFICACIÓN FINAL CALIDAD,NIVEL SELLO EXCELENCIA
0,PLAN ANUAL DE ADQUISICIONES ALCALDÍA MUNICIPIO...,dataset,"Alcaldía Municipal de La Unión, Valle Del Cauca",Función pública,El Plan Anual de Adquisiciones (PAA) de la Alc...,published,"La Unión, Valle del Cauca","Alcaldía de La Unión, Valle del Cauca",Territorial,Valle del Cauca,Anual,2024 Oct 26 02:50:00 PM,2024 Oct 30 07:51:00 PM,2024 Oct 30 07:51:00 PM,8.87,0
1,Administrativos Universidad del Magdalena,dataset,Universidad del Magdalena,Educación,Funcionarios administrativos de planta desde e...,published,Santa Marta,Universidad del Magdalena,Territorial,Magdalena,Anual,2021 Mar 31 07:14:00 PM,2021 Mar 31 07:27:00 PM,2024 Jan 17 02:22:00 PM,8.87,0
2,Evaluación de tierras con fines agrícolas para...,dataset,Unidad de Planificación Rural Agropecuaria - UPRA,Agricultura y Desarrollo Rural,El mapa es el producto resultante de la valida...,published,Bogotá D.C.,"Unidad de Planificación de Tierras Rurales, Ad...",Nacional,Bogotá D.C.,Trienio,2018 Dec 21 03:45:00 PM,2018 Dec 21 04:52:00 PM,2018 Dec 21 04:52:00 PM,8.26,0
3,Informacion_clasificada_y_reservada_Notaria_Pr...,dataset,Notaría Primera del Círculo de Envigado,Función pública,NaN,published,Envigado,Notaría Primera del Círculo de Envigado,Territorial,Antioquia,Anual,2022 Sep 28 11:28:00 PM,2022 Sep 28 11:32:00 PM,2022 Sep 30 10:01:00 PM,7.71,0
4,ACTIVIDADES DE EMPRENDIMIENTO EN MADRID,dataset,Secretaria de Desarrollo economico,"Comercio, Industria y Turismo",Listado de las actividades de emprendimiento e...,published,Madrid,Alcaldía de Madrid,Territorial,Cundinamarca,Anual,2022 Feb 08 03:57:00 PM,2022 Feb 08 04:13:00 PM,2024 Oct 28 02:41:00 PM,8.11,1

In [4]:
df.shape

(19175, 16)

Se carga el dataset utilizando pandas para analizar su estructura
y visualizar las primeras filas del conjunto de datos.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19175 entries, 0 to 19174
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Título                      19175 non-null  str
 1   Tipo de activo              19175 non-null  str
 2   Suministró los datos        16615 non-null  str
 3   Categoría                   17731 non-null  str
 4   Descripción                 16878 non-null  str
 5   Etapa de publicación        19175 non-null  str
 6   Municipio                   18963 non-null  str
 7   Nombre entidad              18963 non-null  str
 8   Orden                       18963 non-null  str
 9   Departamento                18963 non-null  str
 10  Frequencia actualización    18963 non-null  str
 11  Fecha de creación           19175 non-null  str
 12  Fecha de publicación        18753 non-null  str
 13  Fecha última actualización  19175 non-null  str
 14  CALIFICACIÓN FINAL CALIDAD  19175 non-null  float64
 15  NIVEL SELLO EXCELENCIA      19175 non-null  int64
dtypes: float64(1), int64(1), str(14)
memory usage: 2.3 MB

Este paso permite conocer:

- número de registros
- tipos de datos
- valores nulos

In [6]:
df.describe()

       CALIFICACIÓN FINAL CALIDAD  NIVEL SELLO EXCELENCIA
count                19175.000000            19175.000000
mean                     7.955029                0.185554
std                      0.922667                0.389962
min                      0.850000                0.000000
25%                      7.490000                0.000000
50%                      8.000000                0.000000
75%                      8.520000                0.000000
max                      9.890000                2.000000

Se calculan estadísticas descriptivas del dataset como:

- media
- desviación estándar
- valores mínimos y máximos
- percentiles

Revisión de datos nulos

In [7]:
df.isnull().sum()

Título                           0
Tipo de activo                   0
Suministró los datos          2560
Categoría                     1444
Descripción                   2297
Etapa de publicación             0
Municipio                      212
Nombre entidad                 212
Orden                          212
Departamento                   212
Frequencia actualización       212
Fecha de creación                0
Fecha de publicación           422
Fecha última actualización       0
CALIFICACIÓN FINAL CALIDAD       0
NIVEL SELLO EXCELENCIA           0
dtype: int64

Se identifican valores faltantes para determinar si es necesario:

- eliminarlos
- imputarlos
- reemplazarlos

In [8]:
df["Suministró los datos"].fillna("No reportado", inplace=True)
df["Categoría"].fillna("No reportado", inplace=True)
df["Descripción"].fillna("No disponible", inplace=True)
df["Municipio"].fillna("No especificado", inplace=True)

/tmp/ipykernel_10752/2943159137.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Suministró los datos"].fillna("No reportado", inplace=True)
/tmp/ipykernel_10752/2943159137.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Categoría"].fillna("No reportado", inplace=True)
/tmp/ipykernel_10752/2943159137.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Descripción"].fillna("No disponible", inplace=True)
/tmp/ipykernel_10752/2943159137.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Municipio"].fillna("No especificado", inplace=True)

0        La Unión, Valle del Cauca
1                      Santa Marta
2                      Bogotá D.C.
3                         Envigado
4                           Madrid
                   ...
19170                       Itagüí
19171                  Bogotá D.C.
19172                  Bogotá D.C.
19173                     Medellín
19174                    Abejorral
Name: Municipio, Length: 19175, dtype: str